application: gigamunch-omninexus-dev
version: 1
runtime: go
api_version: go1

threadsafe: yes
#default_expiration: 1d?
#max_concurrent_requests: 500

handlers:

- url: /favicon.ico
  static_files: app/favicon.ico
  upload: app/favicon.ico

- url: /
  static_files: app/index.html
  upload: app/index.html

# - url: /test.html
#   static_files: app/test.html
#   upload: app/test.html

#change to be generic
- url: /fonts
  static_dir: app/fonts

- url: /icons
  static_dir: app/icons

- url: /img
  static_dir: app/img

- url: /js
  static_dir: app/js

- url: /css
  static_dir: app/css

- url: /.*
  script: _go_app
#  secure: always

# - url: /_ah/spi/.*
#   script: _go_app
