application: gigamunch-omninexus-dev
# module: default
version: 1
runtime: go
api_version: go1

threadsafe: yes

#max_concurrent_requests: 500

handlers:
- url: /favicon.ico
  static_files: app/favicon.ico
  upload: app/favicon.ico

- url: /robots.txt
  static_files: app/robots.txt
  upload: app/robots.txt

- url: /
  static_files: app/index.html
  upload: app/index.html

#change to be generic
- url: /fonts
  static_dir: app/fonts

- url: /img
  static_dir: app/img

- url: /video
  static_dir: app/video

- url: /js
  static_dir: app/js

- url: /css
  static_dir: app/css

- url: /.*
  script: _go_app
#  secure: always

# - url: /_ah/spi/.*
#   script: _go_app
