application: gigamunch-omninexus-dev
module: default
version: 1
runtime: go
api_version: go1

handlers:
  - url: /.*
    script: _go_app
    secure: always

  - url: /_ah/spi/.*
    script: _go_app
    secure: always

env_variables:
  GIGAMUNCH_PRIVATE_DIR: '/Users/atish/Development/go/src/gitlab.com/atishpatel/Gigamunch-Backend/private'
  PROJECTID: 'gigamunch-omninexus-dev'
