application: gigamunch-omninexus-dev
module: endpoint-cook
version: 1
runtime: go
api_version: go1

handlers:
  - url: /process-order
    script: _go_app
    login: admin

  - url: /.*
    script: _go_app
    secure: always

  - url: /_ah/spi/.*
    script: _go_app
    secure: always

beta_settings:
      cloud_sql_instances: gigasqldb
