application: gigamunch-omninexus-dev
module: default
version: 1
runtime: go
api_version: go1

handlers:
  - url: /remove-closed-posts
    script: _go_app
    login: admin

  - url: /close-post
    script: _go_app
    login: admin

  - url: /notify-muncher
    script: _go_app
    login: admin

  - url: /process-order
    script: _go_app
    login: admin

  - url: /.*
    script: _go_app
    secure: always

  - url: /_ah/spi/.*
    script: _go_app
    secure: always

env_variables:
  GIGAMUNCH_PRIVATE_DIR: '/Users/atish/Development/go/src/gitlab.com/atishpatel/Gigamunch-Backend/private'
