application: gigamunch-omninexus-dev
module: endpoint-gigachef
version: 1
runtime: go
api_version: go1

env_variables:
  GIGAMUNCH_PRIVATE_DIR: '/Users/atish/Development/go/src/github.com/atishpatel/Gigamunch-Backend/private'

handlers:
  - url: /_ah/spi/.*
    script: _go_app
    secure: always

  - url: /.*
    script: _go_app
    secure: always
