application: gigamunch-omninexus-dev
# module: default
module: server
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: common/favicon.ico
  upload: common/favicon.ico

- url: /robots.txt
  static_files: common/robots.txt
  upload: common/robots.txt

- url: /common
  static_dir: common

- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /gigachef/(.*).(html|js|json|css|map)
  static_files: chef/app/\1.\2
  upload: (.*)\.(html|js|json|css|map)
  secure: always

# - url: /gigachef.*
#   static_files: chef/app/index.html
#   upload: chef/app/index.html
#   http_headers:
#     Link: '<chef/app/scripts/app.js>; rel=preload; as=script, <chef/app/elements/elements.html>; rel=preload; as=document, <chef/app/styles/main.css>; rel=preload; as=style'
#   secure: always

- url: (.*).(html|js|json|css|map)
  static_files: \1.\2
  upload: (.*)\.(html|js|json|css|map)
  secure: always

- url: /.*
  script: _go_app
  secure: always

env_variables:
  GIGAMUNCH_PRIVATE_DIR: '/Users/atish/Development/go/src/github.com/atishpatel/Gigamunch-Backend/private'
  PROJECTID: 'gigamunch-omninexus-dev'
